version: '3.8'

services:
  artemis:
    image: mirror.gcr.io/peresadaoleg/artemis-peresada-oleg:2.34.0
    ports:
      - '8161:8161'
      - '61616:61616'
      - '5672:5672'
  redis:
    image: mirror.gcr.io/redis:latest
    ports:
      - '6379:6379'
  postgres:
    image: mirror.gcr.io/postgres:16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - '8180:8080'
    command:
      - start-dev